### ISSUE TITLE
simple chart global annotations don't work

### ISSUE THREAD

**Issue by tarvitz** [iponweb/charts#1]
Hi, I've started using simple chart to deploy my payload and I've noticed that the following snippet works only for labels:

```yaml
settings:
  global:
    annotations: &global-annotations
      responsible: '{{ $.Values.context.responsible }}'
    labels:
      user: '{{ $.Values.context.responsible }}'
  containers:
    defaults:
      imageRef: busybox
      envFrom:
        - configMapRef:
            name: '{{ include "metachart.fullname" $ }}-globals'
            optional: false

#: Here's a workaround for settings.global.annotations, without them Kubernetes resources
#: remain without annotations
annotations:
  <<: *global-annotations
```
