### ISSUE TITLE
ECRAuthorizationToken does not work

### ISSUE THREAD

**Issue by eperdeme** [iponweb/charts#3]
Attempting to use ECRAuthorizationToken the _settings.tpl has the wrong API version in.

```
 ecrauthorizationtokens:
-  apiVersion: generators.external-secrets.io/v1beta1
+  apiVersion: generators.external-secrets.io/v1alpha1
```

```
ecrauthorizationtokens:
  ecr:
    spec:
          region: eu-west-1
          auth:
            jwt:
              serviceAccountRef:
                name: mysvc-account
````
